default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: ankitpatel
  password: 445xpzxn22

development:
  <<: *default
  database: converter_development

test:
  <<: *default
  database: converter_test

production:
  <<: *default
  database: converter_production
  username: postgres
  password: 445xpzxn22