default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: ankitpatel
  password: <%= ENV['ANKIT_PATEL'] %>

development:
  <<: *default
  database: converter_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAMES'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAMES'] %>_production
  username: postgres