# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Dimension.create(title: "Acceleration")
Dimension.create(title: "Angle")
Dimension.create(title: "Area")
Dimension.create(title: "Currency")
Dimension.create(title: "Data Storage")
Dimension.create(title: "Data Transfer Rate")
Dimension.create(title: "Density")
Dimension.create(title: "Electricity")
Dimension.create(title: "Energy")
Dimension.create(title: "Force")
Dimension.create(title: "Force per Length")
Dimension.create(title: "Frequency")
Dimension.create(title: "Fuel Consumption")
Dimension.create(title: "Length")
Dimension.create(title: "Light")
Dimension.create(title: "Mass")
Dimension.create(title: "Mass Flow")
Dimension.create(title: "Power")
Dimension.create(title: "Pressure")
Dimension.create(title: "Speed")
Dimension.create(title: "Temperature")
Dimension.create(title: "Time")
Dimension.create(title: "Torque")
Dimension.create(title: "Volume")

Unit.create(category: "Unit", title: "Meter", dimension: "Length", anchor_value: 1, accuracy: "Exact")
Unit.create(category: "Unit", title: "Kilometer", dimension: "Length", anchor_value: 1000, accuracy: "Exact")
Unit.create(category: "Unit", title: "Millimeter", dimension: "Length", anchor_value: 0.001, accuracy: "Exact")
Unit.create(category: "Unit", title: "Mile", dimension: "Length", anchor_value: 1609.34, accuracy: "Exact")
Unit.create(category: "Unit", title: "Foot", dimension: "Length", anchor_value: 0.3048, accuracy: "Exact")
Unit.create(category: "Unit", title: "Centimeter", dimension: "Length", anchor_value: 0.01, accuracy: "Exact")
Unit.create(category: "Unit", title: "Micrometer", dimension: "Length", anchor_value: 0.000001, accuracy: "Exact")
Unit.create(category: "Unit", title: "Nanometer", dimension: "Length", anchor_value: 0.000000001, accuracy: "Exact")
Unit.create(category: "Unit", title: "Yard", dimension: "Length", anchor_value: 0.9144, accuracy: "Exact")
Unit.create(category: "Unit", title: "Inch", dimension: "Length", anchor_value: 0.0254, accuracy: "Exact")
Unit.create(category: "Unit", title: "Nautical Mile", dimension: "Length", anchor_value: 1852, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Kilometer", dimension: "Area", anchor_value: 1000000, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Meter", dimension: "Area", anchor_value: 1, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Mile", dimension: "Area", anchor_value: 2590000, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Yard", dimension: "Area", anchor_value: 0.836127, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Foot", dimension: "Area", anchor_value: 0.092903, accuracy: "Exact")
Unit.create(category: "Unit", title: "Square Inch", dimension: "Area", anchor_value: 0.00064516, accuracy: "Exact")
Unit.create(category: "Unit", title: "Hectare", dimension: "Area", anchor_value: 10000, accuracy: "Exact")
Unit.create(category: "Unit", title: "Acre", dimension: "Area", anchor_value: 4046.86, accuracy: "Exact")
Unit.create(category: "Football Field", title: "American Football Field", dimension: "Length", anchor_value: 109.728, accuracy: "Precise")
Unit.create(category: "Football Field", title: "American Football Field", dimension: "Area", anchor_value: 5363.6, accuracy: "Precise")
Unit.create(category: "Car", title: "Sedan", dimension: "Length", anchor_value: 4.5, accuracy: "Average")
Unit.create(category: "Unit", title: "Kilobyte", dimension: "Data Storage", anchor_value: 1, accuracy: "Exact")
Unit.create(category: "Unit", title: "Bit", dimension: "Data Storage", anchor_value: 0.000125, accuracy: "Exact")